
package ehealth.controller_db.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataBaseService", targetNamespace = "http://ws.controller_db.ehealth/", wsdlLocation = "https://sde-database.herokuapp.com/ws/people?wsdl")
public class DataBaseService
    extends Service
{

    private final static URL DATABASESERVICE_WSDL_LOCATION;
    private final static WebServiceException DATABASESERVICE_EXCEPTION;
    private final static QName DATABASESERVICE_QNAME = new QName("http://ws.controller_db.ehealth/", "DataBaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sde-database.herokuapp.com/ws/people?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATABASESERVICE_WSDL_LOCATION = url;
        DATABASESERVICE_EXCEPTION = e;
    }

    public DataBaseService() {
        super(__getWsdlLocation(), DATABASESERVICE_QNAME);
    }

    public DataBaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATABASESERVICE_QNAME, features);
    }

    public DataBaseService(URL wsdlLocation) {
        super(wsdlLocation, DATABASESERVICE_QNAME);
    }

    public DataBaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATABASESERVICE_QNAME, features);
    }

    public DataBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceDB
     */
    @WebEndpoint(name = "ServiceDBImplPort")
    public ServiceDB getServiceDBImplPort() {
        return super.getPort(new QName("http://ws.controller_db.ehealth/", "ServiceDBImplPort"), ServiceDB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceDB
     */
    @WebEndpoint(name = "ServiceDBImplPort")
    public ServiceDB getServiceDBImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.controller_db.ehealth/", "ServiceDBImplPort"), ServiceDB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATABASESERVICE_EXCEPTION!= null) {
            throw DATABASESERVICE_EXCEPTION;
        }
        return DATABASESERVICE_WSDL_LOCATION;
    }

}
