
package ehealth.controller_db.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceDB", targetNamespace = "http://ws.controller_db.ehealth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceDB {


    /**
     * 
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonListResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readPersonListRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param idPerson
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readPersonRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdatePersonResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/updatePersonRequest", output = "http://ws.controller_db.ehealth/ServiceDB/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.CreatePersonResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/createPersonRequest", output = "http://ws.controller_db.ehealth/ServiceDB/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.DeletePersonResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/deletePersonRequest", output = "http://ws.controller_db.ehealth/ServiceDB/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "measureTypes", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureTypesResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readMeasureTypesRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.MeasureDefinition
     */
    @WebMethod
    @WebResult(name = "measureType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureType", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureType")
    @ResponseWrapper(localName = "readMeasureTypeResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureTypeResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readMeasureTypeRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readMeasureTypeResponse")
    public MeasureDefinition readMeasureType(
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param idPerson
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonHistoryResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readPersonHistoryRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readPersonHistoryResponse")
    public List<HealthMeasureHistory> readPersonHistory(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param idPerson
     * @param mid
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadPersonMeasureResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readPersonMeasureRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readPersonMeasureResponse")
    public HealthMeasureHistory readPersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/savePersonMeasureRequest", output = "http://ws.controller_db.ehealth/ServiceDB/savePersonMeasureResponse")
    public HealthMeasureHistory savePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdatePersonMeasureResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/updatePersonMeasureRequest", output = "http://ws.controller_db.ehealth/ServiceDB/updatePersonMeasureResponse")
    public HealthMeasureHistory updatePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param idPerson
     * @param before
     * @param after
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureHistoriesByDate", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureHistoriesByDate")
    @ResponseWrapper(localName = "readMeasureHistoriesByDateResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadMeasureHistoriesByDateResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readMeasureHistoriesByDateRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readMeasureHistoriesByDateResponse")
    public List<HealthMeasureHistory> readMeasureHistoriesByDate(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "before", targetNamespace = "")
        XMLGregorianCalendar before,
        @WebParam(name = "after", targetNamespace = "")
        XMLGregorianCalendar after);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.UpdateGoalResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/updateGoalRequest", output = "http://ws.controller_db.ehealth/ServiceDB/updateGoalResponse")
    public Goal updateGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readGoalList", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadGoalList")
    @ResponseWrapper(localName = "readGoalListResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadGoalListResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readGoalListRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readGoalListResponse")
    public List<Goal> readGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readLatestGoalList", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadLatestGoalList")
    @ResponseWrapper(localName = "readLatestGoalListResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.ReadLatestGoalListResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/readLatestGoalListRequest", output = "http://ws.controller_db.ehealth/ServiceDB/readLatestGoalListResponse")
    public List<Goal> readLatestGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveGoal", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.SaveGoal")
    @ResponseWrapper(localName = "saveGoalResponse", targetNamespace = "http://ws.controller_db.ehealth/", className = "ehealth.controller_db.ws.SaveGoalResponse")
    @Action(input = "http://ws.controller_db.ehealth/ServiceDB/saveGoalRequest", output = "http://ws.controller_db.ehealth/ServiceDB/saveGoalResponse")
    public Goal saveGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

}
